# Generated by Django 2.2.16 on 2021-12-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postgroup',
            name='create_datetime',
        ),
        migrations.RemoveField(
            model_name='postgroup',
            name='dept_belong_id',
        ),
        migrations.RemoveField(
            model_name='postgroup',
            name='update_datetime',
        ),
        migrations.AddField(
            model_name='postgroup',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='postgroup',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='postgroup',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
