# Generated by Django 2.2.16 on 2021-12-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211212_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgroup',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='image_url'),
        ),
    ]
