# Generated by Django 2.2.16 on 2021-11-14 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followbook',
            options={'verbose_name': 'Follow book', 'verbose_name_plural': 'Follow book'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profile'},
        ),
    ]
