# Generated by Django 2.2.16 on 2021-11-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20211114_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followbook',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='followbook',
            name='description',
        ),
        migrations.RemoveField(
            model_name='followbook',
            name='modifier',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='modifier',
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='modifier',
        ),
    ]
