# Generated by Django 2.2.16 on 2021-11-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20211113_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name': 'Thông tin máy chủ', 'verbose_name_plural': 'Thông tin máy chủ'},
        ),
        migrations.AlterField(
            model_name='server',
            name='ip',
            field=models.CharField(max_length=32, verbose_name='Địa chỉ ip'),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Tên máy chủ'),
        ),
        migrations.AlterField(
            model_name='server',
            name='os',
            field=models.CharField(max_length=32, verbose_name='Hệ điều hành'),
        ),
        migrations.AlterField(
            model_name='server',
            name='remark',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Nhận xét'),
        ),
    ]
