# Generated by Django 2.2.16 on 2021-11-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20211126_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('enable', 'Enable'), ('disable', 'Disable')], default='enable', max_length=20, verbose_name='status'),
        ),
    ]
