# Generated by Django 2.2.16 on 2021-11-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_auto_20211127_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0, verbose_name='status'),
        ),
    ]
