# Generated by Django 2.2.16 on 2021-11-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_auto_20211127_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.IntegerField(choices=[(1, 1), (0, 0)], default=1, verbose_name='status'),
        ),
    ]
