# Generated by Django 2.2.16 on 2021-12-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
