# Generated by Django 2.2.16 on 2022-01-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20211228_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='VulgarWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('word', models.CharField(max_length=100)),
                ('re_word', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'vulgar',
                'verbose_name_plural': 'vulgar',
            },
        ),
    ]
