# Generated by Django 2.2.16 on 2022-01-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_vulgarword'),
    ]

    operations = [
        migrations.AddField(
            model_name='historysearch',
            name='point',
            field=models.IntegerField(default=1),
        ),
    ]
