# Generated by Django 2.2.16 on 2022-01-14 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_historysearch_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historysearch',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historysearch', to=settings.AUTH_USER_MODEL),
        ),
    ]
