# Generated by Django 2.2.16 on 2021-12-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemedia', '0002_auto_20211212_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
