# Generated by Django 2.2.16 on 2021-12-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logininfor',
            name='loginLocation',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='loginLocation'),
        ),
    ]
