# Generated by Django 2.2.16 on 2022-01-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_log_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
