# Generated by Django 2.2.16 on 2021-11-11 01:07

import apps.vadmin.op_drf.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', apps.vadmin.op_drf.fields.DescriptionField(blank=True, default='', help_text='描述', null=True, verbose_name='描述')),
                ('modifier', apps.vadmin.op_drf.fields.ModifierCharField(blank=True, help_text='该记录最后修改者', max_length=255, null=True, verbose_name='修改者')),
                ('dept_belong_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='数据归属部门')),
                ('update_datetime', apps.vadmin.op_drf.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', apps.vadmin.op_drf.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('title', models.CharField(max_length=1000, verbose_name='name_book')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='books/%Y/%m/%d/', verbose_name='thumbnail')),
                ('author', models.CharField(max_length=300, null=True, verbose_name='author')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('suspension', 'Suspension'), ('new', 'New'), ('full', 'Full')], default='new', max_length=20, verbose_name='status')),
                ('type', models.CharField(max_length=20, verbose_name='type')),
                ('like_count', models.IntegerField(default=0, verbose_name='like_count')),
                ('view_count', models.IntegerField(default=0, verbose_name='view_count')),
                ('star', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='star')),
                ('is_enable', models.BooleanField(default=False, verbose_name='is_enable')),
                ('is_vip', models.BooleanField(default=False, verbose_name='is_vip')),
                ('is_full', models.BooleanField(default=False, verbose_name='is_full')),
                ('is_suggest', models.BooleanField(default=False, verbose_name='is_suggest')),
                ('creator', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Book',
            },
        ),
    ]
