# Generated by Django 2.2.16 on 2021-11-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'image', 'verbose_name_plural': 'image'},
        ),
    ]
