# Generated by Django 2.2.16 on 2021-11-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_image_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.IntegerField(choices=[(1, 1), (0, 0)], default=1, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='reply',
            name='status',
            field=models.IntegerField(choices=[(1, 1), (0, 0)], default=1, verbose_name='status'),
        ),
    ]
