# Generated by Django 2.2.16 on 2021-11-29 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20211128_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagbook',
            name='book',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='book'),
        ),
        migrations.AlterField(
            model_name='tagbook',
            name='tag',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='book.Tag', verbose_name='tag'),
        ),
    ]
