# Generated by Django 2.2.16 on 2021-12-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20211212_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='groups/avatar/%Y/%m/%d/'),
        ),
    ]
