# Generated by Django 2.2.16 on 2021-12-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_group_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupuser',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
