# Generated by Django 2.2.16 on 2021-11-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postgroup',
            options={'verbose_name': 'PostGroup', 'verbose_name_plural': 'PostGroup'},
        ),
        migrations.AddField(
            model_name='postgroup',
            name='status',
            field=models.IntegerField(choices=[(1, 1), (0, 0)], default=1, verbose_name='status'),
        ),
    ]
