# Generated by Django 2.2.16 on 2021-12-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0003_history_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
