# Generated by Django 2.2.16 on 2021-11-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0003_userprofile_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Quản lý menu', 'verbose_name_plural': 'Quản lý menu'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Đăng nhập'),
        ),
    ]
