# Generated by Django 2.2.16 on 2021-11-27 03:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0004_auto_20211123_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Role'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Quan ly nguoi dung', 'verbose_name_plural': 'Quan ly nguoi dung'},
        ),
        migrations.RemoveField(
            model_name='role',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dept',
        ),
        migrations.AlterField(
            model_name='role',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='admin'),
        ),
        migrations.AlterField(
            model_name='role',
            name='dataScope',
            field=models.CharField(choices=[('1', 'Tất cả các quyền dữ liệu'), ('2', 'Quyền đối với dữ liệu tùy chỉnh'), ('3', 'Cơ quan dữ liệu của bộ phận này'), ('4', 'Cơ quan dữ liệu của bộ phận này trở xuống'), ('5', 'Chỉ truy cập dữ liệu cá nhân')], default='1', max_length=8, verbose_name='dataScope'),
        ),
        migrations.AlterField(
            model_name='role',
            name='menu',
            field=models.ManyToManyField(db_constraint=False, to='permission.Menu', verbose_name='menu'),
        ),
        migrations.AlterField(
            model_name='role',
            name='remark',
            field=models.TextField(blank=True, help_text='remark', null=True, verbose_name='remark'),
        ),
        migrations.AlterField(
            model_name='role',
            name='roleKey',
            field=models.CharField(max_length=64, verbose_name='roleKey'),
        ),
        migrations.AlterField(
            model_name='role',
            name='roleName',
            field=models.CharField(max_length=64, verbose_name='roleName'),
        ),
        migrations.AlterField(
            model_name='role',
            name='roleSort',
            field=models.IntegerField(verbose_name='roleSort'),
        ),
        migrations.AlterField(
            model_name='role',
            name='status',
            field=models.CharField(max_length=8, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.TextField(blank=True, null=True, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=40, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='post',
            field=models.ManyToManyField(db_constraint=False, to='permission.Post', verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='remark',
            field=models.TextField(null=True, verbose_name='remark'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ManyToManyField(db_constraint=False, to='permission.Role', verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='secret',
            field=models.CharField(default=uuid.uuid4, max_length=255, verbose_name='secret'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.IntegerField(default=0, verbose_name='user_type'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(db_index=True, max_length=150, unique=True, verbose_name='username'),
        ),
        migrations.DeleteModel(
            name='Dept',
        ),
    ]
