# Generated by Django 2.2.16 on 2021-11-27 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_auto_20211127_1457'),
        ('permission', '0006_auto_20211127_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.Group', verbose_name='group'),
        ),
    ]
